config/routes.rb
Rails.application.routes.draw do
  resources :places

  root 'places#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
  paginates_per 2
  geocoded_by :address
  after_validation :geocode

  validates_presence_of :address
  validates_presence_of :name

  def self.markefy(array)
    markers = []
    array.each do |place|
      markers.push([place.name, place.latitude, place.longitude])
    end
    markers
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def index
    @places = Place.all
    @place_pages = Place.order(:name).page params[:page]
    @markers = Place.markefy(@place_pages)
    @image = 'http://media3.giphy.com/media/M7gtacN7aPNsc/giphy.gif'
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      redirect_to @place
    else
      render :new
    end
  end

  def show
    @place = Place.find(params[:id])
  end

  private

  def place_params
    params.require(:place).permit(:name, :address)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MapPlay</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>MaP PlaY</h1>
    </header>
    <%= yield %>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA9wAasFl3L3uOLJzK469tAc8tC2ch1YYw&callback=initMap"></script>
  </body>
</html>

app/views/places/index.haml
#messages
= paginate @place_pages
- @place_pages.each do |place|
  %h1= link_to place.name, place_path(place)



%div{ style: 'width 1200px;'}
#map{style: 'width: 1200px; height: 1200px;'}

:javascript
  var markers = #{raw @markers}

  var turn_red = function(){
    $('#messages').append("<h1>HEMAN!! YEAH!!!</h1>");
    $('div').scrollTop();
  }

  function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
      center: {lat:  41.390205, lng: 2.154007},
      zoom: 2,
      styles :
      [{"elementType":"geometry","stylers":[{"hue":"#ff4400"},{"saturation":-68},{"lightness":-4},{"gamma":0.72}]},{"featureType":"road","elementType":"labels.icon"},{"featureType":"landscape.man_made","elementType":"geometry","stylers":[{"hue":"#0077ff"},{"gamma":3.1}]},{"featureType":"water","stylers":[{"hue":"#00ccff"},{"gamma":0.44},{"saturation":-33}]},{"featureType":"poi.park","stylers":[{"hue":"#44ff00"},{"saturation":-23}]},{"featureType":"water","elementType":"labels.text.fill","stylers":[{"hue":"#007fff"},{"gamma":0.77},{"saturation":65},{"lightness":99}]},{"featureType":"water","elementType":"labels.text.stroke","stylers":[{"gamma":0.11},{"weight":5.6},{"saturation":99},{"hue":"#0091ff"},{"lightness":-86}]},{"featureType":"transit.line","elementType":"geometry","stylers":[{"lightness":-48},{"hue":"#ff5e00"},{"gamma":1.2},{"saturation":-23}]},{"featureType":"transit","elementType":"labels.text.stroke","stylers":[{"saturation":-64},{"hue":"#ff9100"},{"lightness":16},{"gamma":0.47},{"weight":2.7}]}]
    });

    var contentString = '<div><img src="http://media3.giphy.com/media/M7gtacN7aPNsc/giphy.gif" alt="this is gif"</div>'


    for( i = 0; i < markers.length; i++ ) {

      var infowindow = new google.maps.InfoWindow({
          content: contentString
      });

      var marker = new google.maps.Marker({
        position: {lat: markers[i][1], lng: markers[i][2]},
        map: map,
        animation: google.maps.Animation.BOUNCE,
        title: markers[i][0],
        windowContent: '<h1>' + markers[i][0] + '#{ image_tag(@image) }' + '</h1>'
      });

      marker.addListener('click', function() {
        infowindow.setContent(this.windowContent);
        infowindow.open(map, this);
        turn_red();
      });

    }

  }

app/views/places/new.haml
=form_for @place do |f|
  = f.label :name
  = f.text_field :name
  = f.label :address
  = f.text_field :address
  = f.submit

app/views/places/show.haml
%h1= @place.name
%h1= @place.address
%h1= @place.latitude
%h1= @place.longitude


%div{ style: 'width 800px;'}
  #map{style: 'width: 800px; height: 400px;'}

:javascript
  var lat = #{@place.latitude};
  var lng = #{@place.longitude};
  var map;
  function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: lat, lng: lng},
      zoom: 8
    });

    var contentString = '<div><img src="https://media.giphy.com/media/aTUrF9TPZYy6Q/giphy.gif" alt="this is gif"</div>'

    var infowindow = new google.maps.InfoWindow({
        content: contentString
    });

    var marker = new google.maps.Marker({
      position: {lat: lat, lng: lng},
      map: map,
       animation: google.maps.Animation.BOUNCE,
      title: 'Hello World!'
    });

    marker.addListener('click', function() {
      infowindow.open(map, marker);
    });
  }

=link_to "Home", root_path